// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ─── Matches google-services.json (project: sewamitra-162a9) ───
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgv8Bw6pQAKj2KDa6UIumacz02HIXLYKA',
    appId: '1:1090348965383:android:6329b1f3d7f7b8ccc954a2',
    messagingSenderId: '1090348965383',
    projectId: 'sewamitra-162a9',
    storageBucket: 'sewamitra-162a9.firebasestorage.app',
  );

  // ─── iOS: add GoogleService-Info.plist and fill these in ───
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9vRcCSIuhinM-0_UDXESAVd7Djm_0Ljo',
    appId: '1:1090348965383:ios:777be571916832f3c954a2',
    messagingSenderId: '1090348965383',
    projectId: 'sewamitra-162a9',
    storageBucket: 'sewamitra-162a9.firebasestorage.app',
    iosClientId: '1090348965383-roub60tkg8oesidikl57v4f87tgsqm1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.sewaMitra',
  );
}
